GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hyZXlhIiwiaWF0IjoxNzEzNTUwODEzfQ.-t8NFoDuJ0u0QaZWXBUK1rKuyPn3Nzhscztv788CQx4

###

POST http://localhost:3000/login 
Content-Type: application/json

{
    "username": "Shreya"
}